### ISSUE TITLE
Modulatory connections are drawn to (0,0)

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-gui#1014]
All modulatory connections seem to connect to the top-left corner.  For example:

```python
import nengo
model = nengo.Network()
with model:
    pre = nengo.Ensemble(n_neurons=100, dimensions=1)
    post = nengo.Ensemble(n_neurons=100, dimensions=1)
    learn_conn = nengo.Connection(pre, post,
                                  learning_rule_type=nengo.PES())
    error = nengo.Ensemble(n_neurons=100, dimensions=1)
    nengo.Connection(error, learn_conn.learning_rule)
```

![image](https://user-images.githubusercontent.com/2380772/59126788-e469ff00-8933-11e9-9931-59f046d68f9d.png)

**Comment by astoeckel** [comment]
Thank you for reporting! This should be fixed in #1015, please let me know in case there are any more problems.

Please note that modulatory connections are not displayed correctly in case they target an "arc connection", but this is an issue I was aware of (there is a TODO in the code, I should probably also open an issue for this).
