### ISSUE TITLE
Top-level network must be named "model"

### ISSUE THREAD

**Issue by hunse** [nengo/nengo-gui#102]
The variable name of the top level network must be "model", or else the visualizer can't find it. Could the model be a parameter to `Viz.start()`, rather than relying on the name?

**Comment by tcstewar** [comment]
It is a parameter to the Viz.__init__().  If you don't specify it, then it searches the locals for ```model```.

However, I'm not happy with that as a final solution.  What I'd prefer is to search locals for all networks, and find the top-level one.  This search process is similar to what's needed to generate the names of all the objects, so it's not actually any extra effort (or at least not much extra effort) to do it, but it's not being done at the moment.

**Comment by hunse** [comment]
To me, it doesn't seem problematic to have to pass the top-level network to Vis. If you're creating a Simulator, you have to pass in the top-level network, so it's not surprising as a user to have to pass it to Vis as well. I'm not sure if all the automation actually buys us much. To me, it just seems to hide stuff from the user.

**Comment by tcstewar** [comment]
> To me, it doesn't seem problematic to have to pass the top-level network to Vis. If you're creating a Simulator, you have to pass in the top-level network, so it's not surprising as a user to have to pass it to Vis as well. I'm not sure if all the automation actually buys us much; it just seems to make the whole system more opaque to the user.

The situation I'm thinking of is when a user is just writing code from within an HTML editor (sort of like how the current nengo_gui works) and doesn't have to put the ```nengo.Viz(file=__file__, locals=locals(), model=model)``` line at the end of their script.  In that situation, it would be nice if it automatically detected.  Otherwise, we have to tell everyone to write that code in manually, or we have it automatically generated and tell people "if you call your top-level model something other than ```model```, then edit this line".  Either approach seems problematic.

Indeed, even for expert users, I find that I prefer to type ```nengo.Viz(file=__file__)```  rather than ```nengo.Viz(file=__file__, locals=locals(), model=model)``` so I think there's some advantage in automatically detecting, if it's part of a process that has to be done anyway.

**Comment by tcstewar** [comment]
It's now pretty rare that people manually start the gui, I'm now fine with them explicitly passing in the model as an argument, and if you don't pass it in, it'll assume it's ```model```.  So I don't think it's worth the overhead of having it go an search for a top-level Network and assume that's the model.
