### ISSUE TITLE
Make netgraph items unable to be dragged beyond the bounds of the network they are within

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#125]

**Comment by tcstewar** [comment]
I think the original point of this Issue was to stop the drag from happening at all.  Right now, you are able to drag things beyond the bounds of the network, but they snap back after you drag them.

That said, I like the current behaviour, so I'm not all that worried about dropping this Issue.  But I just thought I'd clarify what it was about.

**Comment by celiasmith** [comment]
Ah fair enough.  I just thought it had been missed :smiley:
