### ISSUE TITLE
Delay on launch (loading message?)

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#16]
On my machine when launching the visualizer there is a ~5 second delay before the graphs start updating.

Should we consider showing the user a message such as "Loading..." until elements start updating?

**Comment by tcstewar** [comment]
Definitely.  I'd meant to add that as an issue.  In Nengo terminology, we call this the "building" phase (it isn't really "loading" data, as it is generating the neural networks and solving for the connection weights).  The ```self.building``` flag in the ```VizSim``` object is keeping track of this, and we should send it to the client somehow (I was thinking via the ```SimControl```, since that's also a natural place to display the fact that we're still building the model)

**Comment by tcstewar** [comment]
Fixed via the play icon
