### ISSUE TITLE
Separate examples from file tree

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-gui#235]
From discussion in #208. We should be making a more stark distinction between user generated scripts (which we can be reasonably sure are in some place that the user can modify) and our provided examples (which are likely to be in a system directory, and therefore are readonly). Something like a separate dropdown menu for examples, rather than having it be part of the same file tree browser.

**Comment by Seanny123** [comment]
Right now, the directory is highlighted in a different colour. Is that enough?

**Comment by tcstewar** [comment]
We definitely need some better way of directing people to them.  There's a lot of confusion evident in this forum post: https://forum.nengo.ai/t/the-tutorials-from-how-to-build-a-brain-in-nengo-2-0/148/6

This is especially the case for people who arrive at Nengo via the book, rather than via the summer school or other tutorials.

One thing that comes to mind is maybe a separate tab for the tutorials?

**Comment by krisfrenette** [comment]
This seems to have been fixed. Going to close this out
