### ISSUE TITLE
Moving and resizing expanded networks is extremely slow

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo-gui#276]
When you have a network with a bunch of stuff in it (e.g. the network in the net.py example) and it is expanded, it will move very slowly when you drag it around in Firefox. This doesn't happen when the network is collapsed.

**Comment by jgosmann** [comment]
Seems fine on my Mac.

**Comment by bjkomer** [comment]
Hmm... I had it happen on both my laptop and desktop (both linux). The effect is more noticeable when both subnet and subsubnet were expanded.

**Comment by studywolf** [comment]
I saw it on my Linux laptop as well! I seen it!

**Comment by tbekolay** [comment]
Just tried this on my Mac laptop... definitely also happens there. I think that this has a pretty simple explanation... that when you drag an expanded network with multiple things in it, we're updating the transform property of every single element in there. We should look at the snippet of code that does that; probably it can be rewritten to be more performant (since Chrome does an okay, but still not perfect, job of rendering it smoothly; it might just have our implementation slightly more tuned for speed).

**Comment by tcstewar** [comment]
One thing to check for is whether we're updating transform multiple times...  that was the culprit in the past, but I thought I get rid of all the cases where I was accidentally doing that.

**Comment by Seanny123** [comment]
Replicated on Chrome

**Comment by tbekolay** [comment]
One thing that we can do to fix things (at least in some cases) is to set the `shape-rendering` CSS property on our root SVG element to `optimizeSpeed`, which should propagate to all of the shapes. See [this doc for more details](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering).

**Comment by krisfrenette** [comment]
I just tested this in both Firefox, and Chrome and I am not seeing this issue anymore. I am going to close this as it may have been browser related and a lot of updates have been done since the original report of the issue.
