### ISSUE TITLE
Make Value plots look pretty

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-gui#4]
- show start and end times on x-axis, rather than the current approach with a single unreadable number flying past
- show label on the title bar
- colors for different lines
- optional legend?
- ability to turn on and off different lines (without the bug in the nengo 1.4 where changing what lines are on changes the color mapping)

**Comment by cchan987** [comment]
For colouring the different lines, @tcstewar has code for selecting optimal colour patterns? Can you please post when you get a chance? Thanks!

**Comment by jgosmann** [comment]
I don't have code, but can provide you with several references about visualization in general. Regarding color in general you might want to look at
* [Choosing colors for data visualization](http://www.perceptualedge.com/articles/b-eye/choosing_colors.pdf)
* [Choosing Color Palettes for Statistical Graphics](http://epub.wu.ac.at/1404/)
* [Points of view: Color coding](http://www.nature.com/nmeth/journal/v7/n8/full/nmeth0810-573.html)
* [Points of view: Color blindness](http://www.nature.com/nmeth/journal/v8/n6/full/nmeth.1618.html)

Instead of coming up with our own colors we could also just copy the [palette of some other library like Seaborn](http://stanford.edu/~mwaskom/software/seaborn/tutorial/color_palettes.html#palette-tutorial) (with developers paying attention to things like a sane color scheme, somewhat in contrast to matplotlib).

[Colorbrewer is also a useful tool for creating color palettes.](http://colorbrewer2.org/)

Finally, I have [some code where I experimented with creating color palettes automatically](https://github.com/jgosmann/neat-plots/tree/master/neatplots).

**Comment by tcstewar** [comment]
Cool!  Nice collection of links there.  :)

I'll track down my code and post it here.....
