### ISSUE TITLE
Make sliders look pretty

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-gui#5]
- Add a line showing where they can move
- Show the numerical value at the top
- Shortcut for zeroing sliders
- Move sliders automatically in accordance with their default value
- Jump time forward if you move the sliders (you can't change values in the past)
  - in Nengo 1.4 this was implemented by having the sliders be deactivated when you're looking at past data, but I think this time just jumping forward in time to the present would be clearer.

**Comment by cchan987** [comment]
Just an fyi
Issue to take note of: 
Was working on an idea for zeroing the sliders by double clicking them. 
This ran into conflict with the onmousedown event that brings the element to the top when clicked on. 
An element could never be double clicked since as soon as mousedown occurs the element is removed and re-added.
Experimenting with alternate methods
