### ISSUE TITLE
Top toolbar should hamburger-ize when too small

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-gui#666]
It would be nice if elements in the top toolbar (maybe not all, but some) get collapsed into a dropdown menu accessible through a [hamburger](https://en.wikipedia.org/wiki/Hamburger_button) when the top toolbar's width is too small. Right now, if you make the window too narrow it will flow into two separate rows, which isn't great.

**Comment by rsimmons1** [comment]
Looked into this, there are a couple of issues, bootstrap natively supports the collapsible menu which is great, however nengo currently does not use the correct type of nav bar for this, there will need to be a decent overhaul of the html/css because of this. Secondly, there are a lot of design and functionality issues in question when the menu collapses, mainly which items do we keep and what do we do with the file explorer. I implemented a basic collapsible menu keeping all of the items on the left and it was not very functional. We should make a sketch of what the new menu should look like at the next developer meeting.

**Comment by Seanny123** [comment]
Now that we have a new sidebar, @tbekolay are you still of the opinion it should hamburgerize instead just stacking the icons on top of each other? Would you recommend two hamburgers? One for the left-side icons and one for the right-side icons.

**Comment by krisfrenette** [comment]
I am going to close this out as it seems as if it functions decently. If we decide to go really small there are a lot of changes that we will have to consider, and would suggest that we create an issue that covers all of the issues with a small screen.
