### ISSUE TITLE
Having a HUD option

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo-gui#78]
So we were getting a sweet demo at the dev meeting yesterday, and one of the things not done yet was having the figures / plots move with the background, rather they stayed on screen as you scrolled through your network. And this made me think of a heads-up-display, and then thinking how awesome / useful it would be to have that kind of set up. Chris mentioned it being like an oscilloscope, where you're probing different parts of the network and seeing the results displayed in a single space, and I think that that's a good description of it. 

It's pretty different from how we look at things now, but I think it would be a really natural way to analyze / interact with the network. I was thinking it would be something like you make your plot, and then do an options click to make it part of the HUD, and then it moves around with you and shows you signals from whatever you've just clicked on, but however. 

One of the things this would require is some means of either dynamically probing things or like Eric mentioned just probing everything and only storing the data if you're examining it (which was suggested anyway for the issue of not having to rebuild the model if you want to add a plot).

**Comment by tcstewar** [comment]
After some discussion in the dev meeting, I'm peeling off two aspects of this issue into separate issues: #849 (putting a plot on an overlay HUD-like thing), and #850 (having a plot that can have multiple sources and you can switch between them).  Together, these would give most of the functionality described here, and those two components would be useful in and of themselves.

The more complex aspect of this Issue would be doing this with dynamic probing (instead of grabbing everything and only storing/showing the data if you're plotting it), which requires some sneaky Nengo trickery at the moment.  Eventually, we would like an official way to add Probes, Connections, and/or Nodes on the fly, but that's a much larger issue and would need its own Nengo Enhancement Proposal.

**Comment by studywolf** [comment]
can you make an issue for the last point too?

**Comment by tcstewar** [comment]
> can you make an issue for the last point too?

Sure...  I assume that should be a core nengo issue, though.

**Comment by studywolf** [comment]
yeah i dunno, should there still be something here because the end goal is a GUI feature?

**Comment by tcstewar** [comment]
> yeah i dunno, should there still be something here because the end goal is a GUI feature?

I think #849 and #850 get pretty close to what you're requesting here...  but if Nengo does eventually get the ability to create Connections and Nodes on the fly, then we'd want to take advantage of that.  I guess I was just thinking that it's so far into the future....  but it doesn't hurt to have an Issue lying around here, I guess.  

That said, it might be a big enough thing that'd it'd count as requiring a full NEP https://github.com/nengo/enhancement_proposals
