### ISSUE TITLE
jupyter not finding 'model'?

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo-gui#846]
i'm getting this error: 

![untitled](https://cloud.githubusercontent.com/assets/2473097/21615464/a6971ec0-d1ab-11e6-8e6c-4282c5beaa9a.png)

with the most recent versions of nengo and nengo_gui, any thoughts?

**Comment by jgosmann** [comment]
Seems like the editor doesn't get deactivated like it should.
I probably won't have time to look into this for a while ...

**Comment by studywolf** [comment]
any hacks i can do or should i just go back to the last released nengo_gui?

**Comment by jgosmann** [comment]
Going back might be the best option at the moment.

**Comment by studywolf** [comment]
k! thanks! ![happy](https://cloud.githubusercontent.com/assets/2473097/21617341/9f102d92-d1b3-11e6-9ab4-ab8febd4cb63.png)

**Comment by studywolf** [comment]
works when i checkout v0.2.0 fyi

**Comment by jgosmann** [comment]
This seems to work for me with the current master branches of Nengo and Nengo GUI.

**Comment by tcstewar** [comment]
> This seems to work for me with the current master branches of Nengo and Nengo GUI.

This also works for me (Python 2.7.5 and IPython 3.1.0)

@studywolf could you check if it's still happening for you?  I can't see anything that has changed since you posted this that might have fixed it....

**Comment by Seanny123** [comment]
This is still happening to me on the Nengo GUI master (0.3.2.dev0), Python 3.6.3, Jupyter Notebook 5.5.0, Windows 10.

**Comment by arvoelke** [comment]
@Seanny123 does it also work if you checkout v0.2.0? Might be a "fun" use of [git bisect](https://git-scm.com/docs/git-bisect) - to find the relevant nengo_gui commit in between.

This was the last commit before January 3, 2017 (time this issue was posted): https://github.com/nengo/nengo-gui/commit/b892f4970c91c040488bcd26b1564dec2a0bd3da

And this was the commit for v0.2.0: https://github.com/nengo/nengo-gui/commit/41dc4a735ba71c3c256a7fe65423229fdb08e9fb

So git bisect will only take `ceil(log_2(1710-1668)) => 6` checks to find the offending commit. Just make sure to reset the kernel and make sure it's picking up the different commits. A little tedious is all.

**Comment by Seanny123** [comment]
@arvoelke you are correct in saying the last working commit was 0.2
