### ISSUE TITLE
Fix nengo_gui in Safari

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-gui#90]
In Safari, the text does not appear on the items, the scroll-wheel/two-finger zoom is ignored, and dragging in the middle of the item causes resizing rather than moving.

Note that the dragging problem is also what happens in Chrome if you use the touch screen to drag rather than a mouse, so that might be fixed by correctly supporting one-and-two-finger touch gestures.

**Comment by jgosmann** [comment]
Problems (feel free to edit):
* [ ] Text does not appear on netgraph items. The problem here is, that the text is set with the `innerHTML` attribute, which does not exist for SVG elements because it is not HTML (though some browser seem to implement it anyways). [A solution might be found in this SO thread.](https://stackoverflow.com/questions/9723422/is-there-some-innerhtml-replacement-in-svg-xml)
* [ ] Slider handles from the `all_is_relative` branch are hanging to low. Problem here is probably that the `transform` CSS property has also to be given as `-webkit-transform`.
* [ ] Slider handles from the `all_is_relative` branch cannot be clicked to edit the value.
* [ ] Resetting sliders from the `all_is_relative` branch gives `TypeError: undefined is not an object (evaluating 'this.reset_value[i]')` in `viz_slider.js:237`.
* [ ] Sliders from the `all_is_relative` branch are not moving.
* [ ] Speed and time in sim control are shifted downwards.

Apart from that it seems to be mostly working.

**Comment by rsimmons1** [comment]
Any version of Safari 9.0 or above is 100% compatible with nengo_gui without error. Finding older versions of safari to test nengo_gui can be difficult because apple only keeps the most recent version of safari available for download.

**Comment by tcstewar** [comment]
It seems to be all working in recent versions of Safari, so yay ignoring a problem until it goes away!  :)
