### ISSUE TITLE
Save slider values in config file

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#95]

**Comment by tcstewar** [comment]
Hmm..  this one would be a bit tricky, since a slider value is inherently associated with a point in time, so it's not clear what value should get saved.....

**Comment by cchan987** [comment]
> Hmm.. this one would be a bit tricky, since a slider value is inherently associated with a point in time, so it's not clear what value should get saved.....

Perhaps when the slider value is being defined as a function of time it is not saving in the config file. However when it is being defined by the user then it gets put into config file.

**Comment by tcstewar** [comment]
> However when it is being defined by the user then it gets put into config file.

But when the user defines it, they are defining it at a particular point in time.  That's what's difficult to save.  Also, if we are saving this value, then how does the user go back to using the original function of time?

**Comment by tcstewar** [comment]
In the dev meeting discussion, I argued that this time thing noted above makes it unclear what the correct behaviour is.  Since the initial values of the sliders can be set in the code (and maybe eventually in the UI component editor), we'll go with that approach, rather than saving them in the config file.
